CREATE TABLE STUDENT7(
STUDENT_ID NUMBER(4) PRIMARY KEY,
STUDENT_NAME VARCHAR2 (30),
COURSE VARCHAR2 (20),
MARKS NUMBER(3)
);

7a

SET SERVEROUTPUT ON;

-- 1. Create STUDENT table
CREATE TABLE STUDENT (
    STUDENT_ID   NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(50),
    MARKS        NUMBER
);

-- 2. Insert sample records
INSERT INTO STUDENT VALUES (101, 'Rahul', 85);
INSERT INTO STUDENT VALUES (102, 'Priya', 92);
INSERT INTO STUDENT VALUES (103, 'Arun', 78);

COMMIT;


-- 3. Create the stored procedure
CREATE OR REPLACE PROCEDURE GET_STUDENT_DETAILS (
    P_STUDENT_ID   IN  STUDENT.STUDENT_ID%TYPE,
    P_STUDENT_NAME OUT STUDENT.STUDENT_NAME%TYPE,
    P_MARKS        OUT STUDENT.MARKS%TYPE
)
IS
BEGIN
    -- Retrieve student details
    SELECT STUDENT_NAME, MARKS
    INTO P_STUDENT_NAME, P_MARKS
    FROM STUDENT
    WHERE STUDENT_ID = P_STUDENT_ID;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_STUDENT_NAME := 'Student Not Found';
        P_MARKS := NULL;
END;
/
 

-- 4. Anonymous PL/SQL block to call the procedure
DECLARE
    V_STUDENT_ID   STUDENT.STUDENT_ID%TYPE := 101;
    V_STUDENT_NAME STUDENT.STUDENT_NAME%TYPE;
    V_MARKS        STUDENT.MARKS%TYPE;
BEGIN
    -- Call the procedure
    GET_STUDENT_DETAILS(
        V_STUDENT_ID,
        V_STUDENT_NAME,
        V_MARKS
    );

    -- Display returned values
    DBMS_OUTPUT.PUT_LINE('Student ID   : ' || V_STUDENT_ID);
    DBMS_OUTPUT.PUT_LINE('Student Name : ' || V_STUDENT_NAME);
    DBMS_OUTPUT.PUT_LINE('Marks        : ' || V_MARKS);
END;
/
