7b

program 1

SET SERVEROUTPUT ON;

-- 1. Create EMPLOYEE table
CREATE TABLE EMPLOYEE7 (
    EMPLOYEE_ID    NUMBER PRIMARY KEY,
    EMPLOYEE_NAME  VARCHAR2(50),
    MONTHLY_SALARY NUMBER(10,2)
);

-- 2. Insert sample employee records
INSERT INTO EMPLOYEE7 VALUES (101, 'Rahul', 25000);
INSERT INTO EMPLOYEE7 VALUES (102, 'Priya', 30000);
INSERT INTO EMPLOYEE7 VALUES (103, 'Arun', 35000);
INSERT INTO EMPLOYEE7 VALUES (104, 'Sneha', 40000);

COMMIT;


-- 3. Create stored function
CREATE OR REPLACE FUNCTION CALCULATE_ANNUAL_SALARY (
    P_MONTHLY_SALARY IN NUMBER
)
RETURN NUMBER
IS
    V_ANNUAL_SALARY NUMBER;
BEGIN
    -- Calculate annual salary
    V_ANNUAL_SALARY := P_MONTHLY_SALARY * 12;

    -- Return annual salary
    RETURN V_ANNUAL_SALARY;
END;
/
-- 4. Invoke the function using SELECT statement
SELECT
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    MONTHLY_SALARY,
    CALCULATE_ANNUAL_SALARY(MONTHLY_SALARY) AS ANNUAL_SALARY
FROM EMPLOYEE7;
