SELECT * FROM EMPLOYEE;

Q1
CREATE VIEW EMP_VIEW AS
SELECT *
FROM EMPLOYEE;

Q2
CREATE VIEW EMP_BASIC AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, SALARY
FROM EMPLOYEE;

Q3
SELECT *
FROM EMP_VIEW;

Q4
CREATE VIEW IT_EMPLOYEES AS
SELECT *
FROM EMPLOYEE
WHERE DEPARTMENT = 'IT';

Q5
CREATE VIEW HIGH_SALARY AS
SELECT *
FROM EMPLOYEE
WHERE SALARY > 60000;

Q6
CREATE VIEW HYDERABAD_EMP AS
SELECT *
FROM EMPLOYEE
WHERE CITY = 'Hyderabad';

Q7
CREATE VIEW FEMALE_EMP AS
SELECT *
FROM EMPLOYEE
WHERE GENDER = 'Female';

Q8
CREATE VIEW RECENT_EMPLOYEES AS
SELECT *
FROM EMPLOYEE
WHERE HIRE_DATE >= TO_DATE('01-JAN-2020','DD-MON-YYYY');

Q9
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM HIGH_SALARY;

Q10
CREATE OR REPLACE VIEW EMP_BASIC AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME,
       DEPARTMENT, SALARY, CITY
FROM EMPLOYEE;

Q11
CREATE VIEW EMP_SALARY_VIEW AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEE
WITH READ ONLY;

Q12
CREATE VIEW SALES_EMP AS
SELECT *
FROM EMPLOYEE
WHERE DEPARTMENT = 'Sales'
WITH CHECK OPTION;

Q13
UPDATE EMP_BASIC
SET SALARY = 75000
WHERE EMPLOYEE_ID = 101;

COMMIT;

Q14
DELETE FROM EMP_VIEW
WHERE EMPLOYEE_ID = 107;

COMMIT;

Q15
INSERT INTO EMP_BASIC
VALUES (111, 'Ravi', 'Kumar', 'IT', 50000, 'Hyderabad');

COMMIT;

Q16
DESC EMP_BASIC;

Q17
SELECT *
FROM IT_EMPLOYEES;

Q18
SELECT *
FROM HIGH_SALARY
WHERE SALARY > 70000;

Q19
SELECT *
FROM FEMALE_EMP;

Q20
SELECT FIRST_NAME, SALARY
FROM HYDERABAD_EMP;

Q21
DROP VIEW EMP_VIEW;

Q22
DROP VIEW HIGH_SALARY;

Q23
DROP VIEW EMP_BASIC;

Q24
CREATE VIEW HR_EMPLOYEES AS
SELECT *
FROM EMPLOYEE
WHERE DEPARTMENT = 'HR';

Q25
CREATE VIEW MARKETING_EMP AS
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT, SALARY
FROM EMPLOYEE
WHERE DEPARTMENT = 'Marketing';

Q26
CREATE VIEW TOP_EARNERS AS
SELECT *
FROM EMPLOYEE
WHERE SALARY > 70000;

Q27
CREATE VIEW EMP_CITY AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, CITY
FROM EMPLOYEE;
q1
CREATE VIEW EMP_VIEW AS
SELECT *
FROM EMPLOYEES; 

q2
CREATE VIEW EMP_BASIC AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, SALARY
FROM EMPLOYEES; 

q3
SELECT *
FROM EMP_VIEW; 

q4
CREATE VIEW IT_EMPLOYEES AS
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT = 'IT'; 

q5
CREATE VIEW HIGH_SALARY AS
SELECT *
FROM EMPLOYEES
WHERE SALARY > 60000; 

q6
CREATE VIEW HYDERABAD_EMP AS
SELECT *
FROM EMPLOYEES
WHERE CITY = 'Hyderabad'; 

q7
CREATE VIEW FEMALE_EMP AS
SELECT *
FROM EMPLOYEES
WHERE GENDER = 'Female'; 
q8
CREATE VIEW RECENT_EMPLOYEES AS
SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE >= '01-JAN-2020'; 

q9
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM HIGH_SALARY; 
q10
CREATE OR REPLACE VIEW EMP_BASIC AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, SALARY, CITY
FROM EMPLOYEES; 

q11
CREATE VIEW EMP_SALARY_VIEW AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WITH READ ONLY; 

-q12
CREATE VIEW SALES_EMP AS
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT = 'Sales'
WITH CHECK OPTION; 
q13
UPDATE EMP_BASIC
SET SALARY = SALARY + 5000 
WHERE EMPLOYEE_ID = 101; 

q14
DELETE FROM EMP_VIEW
WHERE EMPLOYEE_ID = 107; 

q15
INSERT INTO EMP_BASIC (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, SALARY, CITY)
VALUES (110, 'Rahul', 'Sharma', 'IT', 55000, 'Hyderabad'); 

q16
DESCRIBE EMP_BASIC;
 

q17
SELECT *
FROM IT_EMPLOYEES; 

q18
SELECT *
FROM HIGH_SALARY
WHERE SALARY > 70000; 
q19
SELECT *
FROM FEMALE_EMP; 
q20
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM HYDERABAD_EMP; 

q21
DROP VIEW EMP_VIEW; 

q22
DROP VIEW HIGH_SALARY; 
q23
DROP VIEW EMP_BASIC; 

q24
CREATE VIEW HR_EMPLOYEES AS
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT = 'HR'; 

-q25
CREATE VIEW MARKETING_EMP AS
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT = 'Marketing'; 

q26
CREATE VIEW TOP_EARNERS AS
SELECT *
FROM EMPLOYEES
WHERE SALARY > 70000; 
q27
CREATE VIEW EMP_CITY AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, CITY
FROM EMPLOYEES;














